### ISSUE TITLE
Popup not readable in dark mode

### ISSUE THREAD

**Issue by CocaineJohnsson** [Loirooriol/tab-counter-plus#30] opened 2021-01-26 08:06 UTC
![image](https://user-images.githubusercontent.com/53689060/105817126-7e713600-5fb5-11eb-99c9-7d0d5ea25646.png)

Does not render correctly on dark themes.

~~Duplicate of #15?~~

EDIT: removed passive and active aggressive tone, it was unprofessional of me.

**Comment by Loirooriol** [comment] 2021-01-26 10:19
Oh, no, that's not a duplicate of #15 which is about the counter in the toolbar! The problem that you are getting is that the popup has a dark background, which I didn't know it could happen. This is what I get in Ubuntu desktop when I choose a dark Firefox theme, and in the add-on setting I choose a white text color:

![Screenshot_20210126_110511](https://user-images.githubusercontent.com/7477678/105831375-ea0fcf00-5fc6-11eb-8ae4-2a3552af61cd.png)

What system are you using? The top header seems like a mobile thing? Note the add-on is not officially supported on Firefox for Android.

I guess it would be a matter of either forcing the popup background to be white, or using `@media (prefers-color-scheme: dark)`. I can fix this, unlike #15. Thanks for the report.

**Comment by CocaineJohnsson** [comment] 2021-01-26 10:31
Waterfox-current 2020.10 on arch linux (hawkeye1176477's repo, KPE patchset), firefox ESR with a privacy focused patchset

I assume it must be fixable since other addons like uBlock Origin, DecentralEyes, and Privacy Badger work correctly. If this is a waterfox bug I'll go and report it to them as well.

Forcing white works, or detecting dark themes and picking a different font colour. either is fine honestly.


P.S Sorry for the ~~passive aggressive~~ active aggressive OG title by the way, I got annoyed with the way you responded but it was unprofessional of me so an apology is in order

**Comment by Loirooriol** [comment] 2021-01-26 10:55
OK thanks, I will try to reproduce. I didn't know Waterfox supported webextensions.

And my reply to the review was also passive-aggressive, sorry I was too quick to jump to conclusions.

**Comment by Loirooriol** [comment] 2021-01-30 22:43
I have tried installing the hawkeye1176477 waterfox-current 2020.10 on Kubuntu 20.04, but basically it looks like Firefox, and I get a white background. Not sure how you got that kind of mobile-ish popup from the image.

This might be a Waterfox bug indeed, seems Firefox used to have similar problems but they fixed it in https://bugzil.la/1449933

But anyways, setting a background manually should work. Getting the colors from `browser.theme.getCurrent()` would be nice, but requesting the `theme` permission seems overkill.

Note to self: the arrow of the panel gets the color from the body, so I should set the background there, not in the `:root`.

**Comment by CocaineJohnsson** [comment] 2021-01-31 00:42
Gotcha, I'll push a report to waterfox as well then.

**Comment by CocaineJohnsson** [comment] 2021-01-31 00:44
I'm not really sure what you mean by mobile looking popup, that's just what they look like when invoked from the overflow menu

**Comment by Loirooriol** [comment] 2021-01-31 19:19
Ah, the overflow menu. It reminded me of the typical UI of mobile apps.

I still can't reproduce with that:

![White background](https://user-images.githubusercontent.com/7477678/106394725-5131e700-63fe-11eb-834e-0dc1097c6054.png)

I have checked my code, I'm using `"browser_style": true` to request the browser to set the appropriate default styles, and I'm not changing the text color nor the background. So it's not really my fault if the text is not readable.

However, since `browser_style` is not using the theme ([bug 1455960](https://bugzilla.mozilla.org/show_bug.cgi?id=1455960)), it may be better to:
 - Set `browser_style: false`
 - Copy the relevant styles from `chrome://browser/content/extension.css`
 - Use `@media (prefers-color-scheme: dark)` to change background and text color.

**Closed** 2021-01-31 21:18 UTC
Labels: bug
